# ===================================================================
# JHipster Sample Spring Cloud Config. PROD Config.
# ===================================================================

# Property used on app startup to check the config server status
configserver:
    name: JHipster Registry config server with prod profile - karthik
    status: Connected to the JHipster Registry config server!

# Default JWT secret token (to be changed in production!)
jhipster:
    security:
        authentication:
            jwt:
                secret: 27e99d13e023b1075bd3408898567606bab44ad8

# Enable /management/logfile endpoint for all apps
logging:
    path: /tmp
    file: ${spring.application.name}.log
